# Generated by Django 3.1.7 on 2021-03-11 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210311_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_responsibility',
            new_name='job_description',
        ),
    ]
